### ISSUE TITLE
.T attribute evaluates to a pandas DataFrame, not a babypandas DataFrame

### ISSUE THREAD

**Issue by surajrampure** [afraenkel/babypandas#17]
See title. This leads to weird issues in test cases. The only line involving `.T` in `bpd.py` is

```py
self.T = _lift_to_pd(self._pd.T)
```

and `_lift_to_pd` seems to convert objects that are `pandas` DataFrames to `babypandas` DataFrames, but that doesn't seem to be happening here. @eldridgejm any ideas?

**Comment by eldridgejm** [comment]
`lift_to_pd` is a higher order function which takes in a function and returns a wrapped version whose output is "lifted" to a BabyPandas object, when appropriate. If the item passed into `lift_to_pd` is not callable, it is immediately returned without modification.

In this case, `self.T = _lift_to_pd(self._pd.T)` wasn't working as expected because `self._pd.T` is not a function, but rather a pandas DataFrame. So `_lift_to_pd` just returned the original dataframe, unmodified.

This also results in a separate "bug" -- `self.T` is set once and does not change, even if the data frame is mutated. Of course, babypandas favors immutability over mutable methods, so this might never actually happen. Still, I moved `.T` and the other attributes to properties so that they are dynamic.
